set PROD_SERVER=df7436sr382.corp.caixa.gov.br
set PROD_DB=DB5402_SICMC

set DATATABLES=adm.tbTiposControle,conferencia.tbItensConferenciaPorTipoDemanda,conferencia.tbOpcoesConferencia,conferencia.tbStatus,conferencia.tbTiposContratacaoPorSistema,conferencia.tbTiposDemanda,config.uploaders,conquiste.tbIndicadoresParametros,convenio.tbCategorias,convenio.tbSistemas,convenio.tbSituacoes,convenio.tbTiposAlcada,convenio.tbTiposCobranca,convenio.tbTiposContratacao,convenio.tbTiposIndexadorTarifa,convenio.tbTiposModalidade,convenio.tbTiposRepasse,convenio.tbTiposTransmissao

set DEV_SERVER=CCTDCDADNT0028.corp.caixa.gov.br
set DEV_DB=SICMCTeste